# Generated by Django 5.0 on 2023-12-10 11:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LoanApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4)),
            ],
        ),
        migrations.CreateModel(
            name="LoanDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("established_year", models.PositiveIntegerField()),
                ("loan_amount", models.PositiveIntegerField()),
                ("balance_sheet", models.JSONField()),
                (
                    "loan_application",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="loan_app.loanapplication",
                    ),
                ),
            ],
        ),
    ]
